import type { Event, EventCategory } from '../types/index.js'

/**
 * PLACEHOLDER EVENTS.
 * These are sample listings that demonstrate the layout and registration flow.
 * They are flagged `isPlaceholder` and labelled "Sample" in the UI.
 * Replace with confirmed events (or connect eventService to your backend).
 */
export const events: Event[] = [
  {
    isPlaceholder: true,
    slug: 'foundations-bible-study',
    title: 'Foundations: Weekly Bible Study',
    category: 'bible-study',
    summary: 'A welcoming weekly study for anyone who wants to read the Bible with others.',
    description: [
      'Foundations is our entry point into Bible study. Each week we read a short passage together, discuss it in small groups and pray.',
      'Whether you have read the Bible for years or are opening it for the first time, you are welcome.',
    ],
    startsAt: '2026-10-06T19:00:00',
    timeLabel: '7:00 – 8:30 PM · time zone TBC',
    format: 'online',
    location: 'Online (link sent after registration)',
    speaker: { name: 'Speaker to be announced' },
    image: 'study-group-table',
    registrationStatus: 'open',
  },
  {
    isPlaceholder: true,
    slug: 'night-of-prayer-for-the-nations',
    title: 'Night of Prayer for the Nations',
    category: 'prayer',
    summary: 'An evening of worship and intercession for the world.',
    description: [
      'Join us for an extended evening of worship, Scripture and prayer for the nations.',
      'Guided prayer segments make it easy to take part, whether you pray aloud or silently.',
    ],
    startsAt: '2026-10-16T20:00:00',
    timeLabel: '8:00 – 10:00 PM · time zone TBC',
    format: 'both',
    location: 'Online & venue to be confirmed',
    speaker: { name: 'Prayer team (to be announced)' },
    image: 'nugget-point-sunset',
    registrationStatus: 'open',
  },
  {
    isPlaceholder: true,
    slug: 'community-fellowship-evening',
    title: 'Community Fellowship Evening',
    category: 'community',
    summary: 'Food, conversation and friendship — a relaxed night to meet the community.',
    description: [
      'A relaxed evening to meet others in Global Harvest, share a meal and hear what’s coming up.',
      'Bring a friend — especially someone who’s curious about faith.',
    ],
    startsAt: '2026-10-24T18:00:00',
    timeLabel: '6:00 – 9:00 PM · time zone TBC',
    format: 'in-person',
    location: 'Venue to be confirmed',
    image: 'bible-study-outdoor',
    registrationStatus: 'open',
    capacity: 60,
  },
  {
    isPlaceholder: true,
    slug: 'sent-mission-vision-evening',
    title: 'SENT: Mission Vision Evening',
    category: 'mission',
    summary: 'Discover what it means to be sent — locally and to the nations.',
    description: [
      'An evening exploring God’s heart for the world and practical ways to get involved in mission.',
      'Includes teaching from Scripture, time for questions and prayer for those considering serving.',
    ],
    startsAt: '2026-11-07T18:30:00',
    timeLabel: '6:30 – 8:30 PM · time zone TBC',
    format: 'both',
    location: 'Online & venue to be confirmed',
    speaker: { name: 'Speaker to be announced' },
    image: 'cliff-sea-sunset',
    registrationStatus: 'open',
  },
  {
    isPlaceholder: true,
    slug: 'global-harvest-launch-gathering',
    title: 'Global Harvest Launch Gathering',
    category: 'special',
    summary: 'Celebrate the launch of Global Harvest with worship, vision and prayer.',
    description: [
      'Be part of our launch gathering — an evening of worship, vision-casting and prayer for the community God is building.',
      'Details, venue and livestream information will be shared with registered guests.',
    ],
    startsAt: '2026-11-21T17:00:00',
    timeLabel: '5:00 – 8:00 PM · time zone TBC',
    format: 'both',
    location: 'Venue & livestream to be confirmed',
    speaker: { name: 'Speakers to be announced' },
    image: 'hero-sunset-coast',
    registrationStatus: 'waitlist',
  },
  {
    isPlaceholder: true,
    slug: 'advent-scripture-and-prayer',
    title: 'Advent: Scripture & Prayer Series',
    category: 'bible-study',
    summary: 'Four weeks preparing for Christmas through the promises of Scripture.',
    description: [
      'A four-week Advent series reading the promises of the coming King, with a short reflection and prayer each week.',
    ],
    startsAt: '2026-12-02T19:00:00',
    timeLabel: '7:00 – 8:00 PM · time zone TBC',
    format: 'online',
    location: 'Online',
    image: 'bible-soft-light',
    registrationStatus: 'open',
  },
  {
    isPlaceholder: true,
    slug: 'prayer-and-worship-evening',
    title: 'Prayer & Worship Evening',
    category: 'prayer',
    summary: 'An evening of sung worship and prayer.',
    description: ['A past sample event showing how completed events appear in the archive.'],
    startsAt: '2026-09-12T19:00:00',
    timeLabel: '7:00 – 9:00 PM · time zone TBC',
    format: 'both',
    location: 'Online & venue to be confirmed',
    image: 'bible-soft-light',
    registrationStatus: 'closed',
  },
  {
    isPlaceholder: true,
    slug: 'introduction-to-global-harvest',
    title: 'Introduction to Global Harvest',
    category: 'community',
    summary: 'An information session for people interested in joining.',
    description: ['A past sample event showing how completed events appear in the archive.'],
    startsAt: '2026-08-29T11:00:00',
    timeLabel: '11:00 AM – 12:00 PM · time zone TBC',
    format: 'online',
    location: 'Online',
    image: 'students-park-bibles',
    registrationStatus: 'closed',
  },
]

export const eventCategories: { value: EventCategory | 'all'; label: string }[] = [
  { value: 'all', label: 'All' },
  { value: 'bible-study', label: 'Bible Study' },
  { value: 'prayer', label: 'Prayer' },
  { value: 'community', label: 'Community' },
  { value: 'mission', label: 'Mission' },
  { value: 'special', label: 'Special Events' },
]

export const categoryLabel = (c: EventCategory) => eventCategories.find((x) => x.value === c)?.label ?? c
