/* eslint-disable */
// Generated by scripts/optimize-images.mjs — do not edit by hand.
export const imageManifest = {
  "bible-golden-light": {
    "width": 2400,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "An open Bible with tabs in warm golden light",
    "credit": "Freepik (free license)",
    "color": "rgb(104 56 24)",
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JZACdMoRwACF9Gtk6W/Ur6AD9+9WP7VNxz/QIJ0k6FbUZe9RBo1/VXpzKrvfCiinq/8XPHRp5GCRqv6boZSsqK0KvoS/GFl9QFAAA"
  },
  "bible-soft-light": {
    "width": 2400,
    "height": 3600,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "An open Bible resting in soft natural light",
    "credit": "Freepik (free license)",
    "color": "rgb(248 248 248)",
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACwBQCdASoYACQAPu1mq08ppaOiJW5hMB2JQBmDiA+T2kuWG5QaMV60LLIfyR/r2WQu5iG76AAA/snEGC0cEQJlOzCkfijGHgvS/hjjyHSHV7fnD3SHHpA4qeqxgnEn6tj6Ug9qH626+JL5I4xGUcph6L5Dau9ERWd/DPiARknwfzuItRjiUBgy6vlWvzi7iAAAAA=="
  },
  "bible-study-outdoor": {
    "width": 2400,
    "height": 1602,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "A small group reading and discussing the Bible at an outdoor table",
    "credit": "Freepik (free license)",
    "color": "rgb(56 40 40)",
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoYABAAPu1mqk4ppaOiMAgBMB2JYwCsABEkklw5HyG1UgAA4PaAB2CSPWvwGxRn/oGRrPl0KigvUYH0NHwcKn8TEAbeWrDPbxtqRNW9Lj7tRjZj7mSPQIAA"
  },
  "cliff-sea-sunset": {
    "width": 2400,
    "height": 1120,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "Sea cliffs and a long coastline at sunset",
    "credit": "Freepik (free license)",
    "color": "rgb(40 40 40)",
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoYAAsAPu1orU2ppqSiMAgBMB2JQAALdrHEWOg6PpqSAAD8jtv4eUrnx0RxAztNTWb894CgcxPruKBMrQ5wdvjnhEQKKIAA"
  },
  "hero-sunset-coast": {
    "width": 2400,
    "height": 1062,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "Aerial view of a coastline glowing under an orange sunset sky",
    "credit": "Freepik (free license)",
    "color": "rgb(56 56 56)",
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoYAAsAPu1kq04ppaQiMAgBMB2JbACdAB4IujzeG/DdaqAA7lbVP5nfHWUw55SI9rjw4Cx2q+zz9t24ubDu72jNZE3Lu4VimIAcvDHNmIkAoAAA"
  },
  "nugget-point-sunset": {
    "width": 2400,
    "height": 1440,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "Sun setting over the ocean beyond a rocky headland and lighthouse",
    "credit": "Freepik (free license)",
    "color": "rgb(8 8 8)",
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBACdASoYAA4APu1kqk4ppaQiMAgBMB2JaACdMoAC+Ls5F9a9Z/euWAD5yJKbAGKcXRAJgmmZPSKWrzqylyJ8HcnL+0TbtmFQVx95coXX+Ks6Y6Hp/SRq2iPNxlMgpxgAAA=="
  },
  "ocean-dark": {
    "width": 2400,
    "height": 1198,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "Dark ocean water with light catching the waves",
    "credit": "Freepik (free license)",
    "color": "rgb(8 40 56)",
    "lqip": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAwCdASoYAAwAPu1kqk2ppaQiMAgBMB2JZQCsAB6/az5J9dPNy7QA/hzd0CeCBtkeOOsdPy6IZ7AA"
  },
  "ocean-teal": {
    "width": 2400,
    "height": 1350,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "Overhead view of rippling deep blue ocean water",
    "credit": "Freepik (free license)",
    "color": "rgb(8 88 120)",
    "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAwCdASoYAA0APu1iqU2ppaQiMAgBMB2JQBOgBZZt0AAA/uRh8UJPbKw/AkrVm6fOHdnnZ2BlW5hb/MTmjYHgAAA="
  },
  "students-park-bibles": {
    "width": 2400,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "Students sitting on the grass in a park reading together",
    "credit": "Freepik (free license)",
    "color": "rgb(248 248 248)",
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoYABAAPu1kqk4ppaQiMAgBMB2JQAAJQShmCgsXv70jLIAA/u1xVrqMva5OcXJGY4/hEeZGTAZNaA1j63rl/nvUf+56c28GMU10xBzZv0aRFkOdYy8IxFF5Twk8giRlEuK4AA=="
  },
  "study-group-table": {
    "width": 2400,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1600,
      2400
    ],
    "alt": "Three young adults studying the Bible together at a table",
    "credit": "Freepik (free license)",
    "color": "rgb(120 88 40)",
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwBACdASoYABAAPu1iqk2ppaQiMAgBMB2JZgCxC8ADAz/TG7UFw/8kOwAA/m6LFS1/KWmay9lfUU3FvcsSpYMtuI6HZiUWD7Rfg568fQ+Gdek1e/EM3L1qQCxfA1MAAAA="
  }
} as const

export type ImageName = keyof typeof imageManifest
