/**
 * Converts source photography in assets-src/photos into responsive WebP
 * variants in public/images and writes a typed manifest to
 * src/content/images.generated.ts (dimensions, srcset widths, blur placeholder).
 *
 * Usage: npm run images
 * To add a photo: drop a .jpg into assets-src/photos, add alt text + credit
 * in the META map below, and re-run the script.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'

const ROOT = path.resolve(import.meta.dirname, '..')
const SRC = path.join(ROOT, 'assets-src/photos')
const OUT = path.join(ROOT, 'public/images')
const MANIFEST = path.join(ROOT, 'src/content/images.generated.ts')
const WIDTHS = [480, 800, 1200, 1600, 2400]

const FREEPIK = 'Freepik (free license)'
/** Alt text and credits. Alt text describes the image for screen-reader users. */
const META = {
  'hero-sunset-coast': { alt: 'Aerial view of a coastline glowing under an orange sunset sky', credit: FREEPIK },
  'nugget-point-sunset': { alt: 'Sun setting over the ocean beyond a rocky headland and lighthouse', credit: FREEPIK },
  'cliff-sea-sunset': { alt: 'Sea cliffs and a long coastline at sunset', credit: FREEPIK },
  'coast-sunset-brazil': { alt: 'Calm sea and shoreline beneath a colourful sunset sky', credit: FREEPIK },
  'ocean-dark': { alt: 'Dark ocean water with light catching the waves', credit: FREEPIK },
  'ocean-teal': { alt: 'Overhead view of rippling deep blue ocean water', credit: FREEPIK },
  'study-group-table': { alt: 'Three young adults studying the Bible together at a table', credit: FREEPIK },
  'bible-study-outdoor': { alt: 'A small group reading and discussing the Bible at an outdoor table', credit: FREEPIK },
  'students-park-bibles': { alt: 'Students sitting on the grass in a park reading together', credit: FREEPIK },
  'bible-golden-light': { alt: 'An open Bible with tabs in warm golden light', credit: FREEPIK },
  'bible-soft-light': { alt: 'An open Bible resting in soft natural light', credit: FREEPIK },
  'bible-by-the-shore': { alt: 'An open Bible on a wooden boardwalk near a sandy shore', credit: FREEPIK },
  'reading-bible-park': { alt: 'A young man reading the Bible on a park bench', credit: FREEPIK },
  'walking-with-bible': { alt: 'A man walking along a boardwalk carrying a Bible', credit: FREEPIK },
  'prayer-circle-park': { alt: 'Four women holding hands in a circle, praying together in a park', credit: FREEPIK },
  'prayer-friends-park': { alt: 'Friends standing in a circle holding hands in prayer outdoors', credit: FREEPIK },
  'prayer-hands-circle': { alt: 'Close view of people joining hands together in prayer', credit: FREEPIK },
  'community-young-adults': { alt: 'Young adults laughing together over coffee', credit: FREEPIK },
  'community-cafe': { alt: 'Friends talking and sharing coffee at a café table', credit: FREEPIK },
  'friends-intercultural': { alt: 'Smiling friends from different backgrounds standing together outdoors', credit: FREEPIK },
  'worship-singing': { alt: 'A woman singing in worship with her hands raised', credit: FREEPIK },
  'mission-traveler-sunset': { alt: 'A traveller with a backpack looking out over the sea at sunset', credit: FREEPIK },
  'mission-mountain-view': { alt: 'A young man with a backpack overlooking a mountain valley', credit: FREEPIK },
  'serve-hands-together': { alt: 'A group of volunteers joining hands together in a park', credit: FREEPIK },
}

await fs.mkdir(OUT, { recursive: true })
const files = (await fs.readdir(SRC)).filter((f) => /\.(jpe?g|png|webp)$/i.test(f)).sort()
const manifest = {}

for (const file of files) {
  const key = file.replace(/\.[^.]+$/, '')
  const meta = META[key]
  if (!meta) throw new Error(`Missing alt text/credit for "${key}" in scripts/optimize-images.mjs`)

  const input = sharp(path.join(SRC, file)).rotate()
  const { width, height } = await input.metadata()
  const widths = WIDTHS.filter((w) => w <= width)
  // Keep the native size too when it is meaningfully larger than the biggest preset.
  if (!widths.length || width > widths[widths.length - 1] * 1.15) widths.push(width)

  for (const w of widths) {
    const out = path.join(OUT, `${key}-${w}.webp`)
    await input
      .clone()
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: w >= 1600 ? 72 : 76, effort: 5 })
      .toFile(out)
  }

  const lqipBuf = await input.clone().resize({ width: 24 }).blur(1.2).webp({ quality: 40 }).toBuffer()
  const { dominant } = await input.clone().resize({ width: 64 }).stats()
  manifest[key] = {
    width,
    height,
    widths,
    alt: meta.alt,
    credit: meta.credit,
    color: `rgb(${dominant.r} ${dominant.g} ${dominant.b})`,
    lqip: `data:image/webp;base64,${lqipBuf.toString('base64')}`,
  }
  console.log(`✓ ${key} (${widths.join(', ')})`)
}

const body = `/* eslint-disable */
// Generated by scripts/optimize-images.mjs — do not edit by hand.
export const imageManifest = ${JSON.stringify(manifest, null, 2)} as const

export type ImageName = keyof typeof imageManifest
`
await fs.writeFile(MANIFEST, body)
console.log(`\nWrote ${Object.keys(manifest).length} images to public/images and manifest to src/content/images.generated.ts`)
