import type { ImgHTMLAttributes } from 'react'
import { imageManifest, type ImageName } from '../../content/images.generated'
import { cn } from '../../lib/cn'

interface ImgProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, 'src' | 'srcSet' | 'width' | 'height'> {
  name: ImageName | string
  /** Responsive sizes hint, e.g. "(min-width: 1024px) 50vw, 100vw". */
  sizes?: string
  /** Above-the-fold image: load eagerly with high priority. */
  priority?: boolean
  /** Decorative image: empty alt so screen readers skip it. */
  decorative?: boolean
}

/**
 * Responsive, lazy-loaded WebP image with a blurred placeholder.
 * Images are generated by `npm run images` from assets-src/photos.
 */
export function Img({ name, sizes = '100vw', priority, decorative, alt, className, style, ...rest }: ImgProps) {
  // Admin-managed content may reference a full URL (e.g. a Media library asset).
  if (/^(https?:)?\/\//.test(name) || (name.startsWith('/') && name.includes('.'))) {
    return <img src={name} alt={decorative ? '' : (alt ?? '')} loading={priority ? 'eager' : 'lazy'} decoding="async" className={cn('bg-teal-800', className)} style={style} {...rest} />
  }
  const meta = imageManifest[name as ImageName]
  if (!meta) {
    if (import.meta.env.DEV) console.warn(`[Img] Unknown image "${name}"`)
    return null
  }
  const srcSet = meta.widths.map((w) => `/images/${name}-${w}.webp ${w}w`).join(', ')
  const fallback = meta.widths.find((w) => w >= 1200) ?? meta.widths[meta.widths.length - 1]
  return (
    <img
      src={`/images/${name}-${fallback}.webp`}
      srcSet={srcSet}
      sizes={sizes}
      width={meta.width}
      height={meta.height}
      alt={decorative ? '' : (alt ?? meta.alt)}
      loading={priority ? 'eager' : 'lazy'}
      decoding={priority ? 'sync' : 'async'}
      fetchPriority={priority ? 'high' : 'auto'}
      className={cn('bg-cover bg-center', className)}
      style={{ backgroundImage: `url("${meta.lqip}")`, backgroundColor: meta.color, ...style }}
      {...rest}
    />
  )
}
